# Generated by Django 5.1.2 on 2024-11-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
