# Generated by Django 5.1.2 on 2025-01-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0002_alter_comment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='tbl name',
        ),
    ]
